server:
  port: ${SERVER_PORT:8081}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: credit-operations

  profiles:
    active: dev

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

services:
  loan-management:
    base-url: ${LOAN_MANAGEMENT_URL:http://localhost:8082}
    internal-api-key: ${INTERNAL_API_KEY:REPLACE_WITH_AN_INTERNAL_SERVICE_SECRET}

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:credit_operations;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/credit_operations}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect